"""Port: persistence for User. Implemented by infrastructure."""

from typing import Protocol

from domain.accounts.entities import User


class UserRepository(Protocol):
    def get_by_id(self, user_id: int) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def create(self, email: str, password: str, first_name: str = "", last_name: str = "") -> User: ...
    def update_profile(self, user_id: int, *, first_name: str | None = None, last_name: str | None = None) -> User | None: ...
    def update_password(self, user_id: int, new_password: str) -> None: ...
    def authenticate(self, email: str, password: str) -> User | None: ...
    def exists_by_email(self, email: str) -> bool: ...
